name: Terraform Apply

on:
  push:
    branches:
      - origin #MAIN ON PUSH

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.7.5
      
    - name: Terraform Init
      run: terraform init
      
    - name: Terraform Plan
      run: terraform plan -out=tfplan
      env:
        TF_VAR_access_key: ${{ secrets.ACCESS_KEY }}
        TF_VAR_secret_key: ${{ secrets.SECRET_KEY }}
        TF_VAR_region: ${{ secrets.REGION }}
        TF_VAR_bucket_name: ${{ secrets.BUCKET_NAME }}

    - name: Save tfplan artifact
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: tfplan
        path: tfplan

    - name: Terraform Apply
      if: success()
      run: terraform apply tfplan

    - name: Wait for 20sec before Terraform Destroy
      if: success()
      run: sleep 20s

    - name: Terraform Destroy
      run: terraform destroy -auto-approve
      env:
        TF_VAR_access_key: ${{ secrets.ACCESS_KEY }}
        TF_VAR_secret_key: ${{ secrets.SECRET_KEY }}
        TF_VAR_region: ${{ secrets.REGION }}
        TF_VAR_bucket_name: ${{ secrets.BUCKET_NAME }}

  # deploy:
  #   name: Deploy to S3
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v2
      
  #   - name: Set up AWS CLI
  #     uses: aws-actions/configure-aws-credentials@v2
  #     with:
  #       aws-access-key-id: ${{ secrets.ACCESS_KEY }}
  #       aws-secret-access-key: ${{ secrets.SECRET_KEY }}
  #       aws-region: ${{ secrets.REGION }}

  #   - name: Clone other repository
  #     run: git clone 

  #   - name: Copy files to S3
  #     run: aws s3 cp --recursive ./other-repo/static s3://bucket-name/static && aws s3 cp other-repo/index.html s3://bucket-name/index.html